# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Site settings
title: Earthen Capital
email: earthencapital@gmail.com
description: >-
  Expert financial planning and investment advisory services based in West Bengal, India. 
  Specializing in Stock Market, Mutual Funds, Fixed Income, and tailored Wealth Management 
  solutions to help you secure a stable financial future.
baseurl: ""
url: "https://earthencapital.in"

# SEO & Social
author: bob
author_job_title: "Founder & Mutual Fund Distributor"
twitter_username: earthencapital
instagram_username: earthen.capital
facebook_username: earthencapital
youtube_username: "EarthenCapital"

# Business block
business:
  type: "FinancialService"
  phone: "+919476310780"
  logo: "/assets/og-logo.png"
  address: "87XP+27F, near yuvasangha club, Dhekeya, Malancha"
  city: "Kharagpur"
  region: "West Bengal"
  zip: "721304"
  country: "IN"
  latitude: 22.3475722
  longitude: 87.2856648
  hasMap: "https://www.google.com/maps/place/Earthen+Capital/@22.3475722,87.2830899,17z/data=!3m1!4b1!4m6!3m5!1s0x3a1d43892c5a1f33:0x35104b5c65a8c07c!8m2!3d22.3475722!4d87.2856648!16s%2Fg%2F11mrmncrfj"
  arn: "ARN-345670"
  social_links:
    - "https://instagram.com/earthen.capital"
    - "https://facebook.com/earthencapital"
    - "https://youtube.com/@EarthenCapital"
    - "https://www.amfiindia.com/research-information/arn-search"
    - "https://www.google.com/maps/place/Earthen+Capital/@22.3475722,87.2830899,17z/data=!3m1!4b1!4m6!3m5!1s0x3a1d43892c5a1f33:0x35104b5c65a8c07c!8m2!3d22.3475722!4d87.2856648!16s%2Fg%2F11mrmncrfj"

# Social image for previews
image: /assets/og-logo.png

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "bob"
      author_image: "/assets/authors/bob-ghosh.jpg"
      read_time: "5 min read"
      featured: false
      featured_order:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - _pages

permalink: /posts/:title

copyright:
  start_year: 2025

exclude:
  - assets/css/input.css
  - node_modules/
  - package.json
  - package-lock.json
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/